apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /metadata/name
        value: comp-app-pv
      - op: replace
        path: /spec/capacity/storage
        value: 5Gi
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /metadata/name
        value: comp-app-pvc
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: comp-app
      - op: replace
        path: /spec/selector/matchLabels/app
        value: comp-app
      - op: replace
        path: /spec/template/metadata/labels/app
        value: comp-app
      - op: replace
        path: /spec/template/spec/nodeSelector/kubernetes.io~1hostname
        value: worker4
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: comp-app
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: mldrafiee/compression-vnf:latest
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2048Mi"
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/name
        value: comp-storage
      - op: replace
        path: /spec/template/spec/volumes/0/name
        value: comp-storage
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: comp-app-pvc
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: comp-service
      - op: replace
        path: /spec/selector/app
        value: comp-app
