apiVersion: v1
kind: PersistentVolume
metadata:
  name: PLACEHOLDER_PV_NAME
spec:
  capacity:
    storage: PLACEHOLDER_STORAGE
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/vnf-app
