apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER_SERVICE_NAME
spec:
  selector:
    app: PLACEHOLDER_APP_LABEL
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
